spring:
  application:
    name: member-management-system
  profiles:
    active: dev
  flyway:
    baseline-on-migrate: true
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

default:
  user:
    password: 123456

jwt:
  secret: YourVerySecureSecretKeyForJWTTokenGenerationMustBeLongEnoughAtLeast256BitsForHS256Algorithm
  expiration: 86400000
